### ISSUE TITLE
Display not updating

### ISSUE THREAD

**Issue by jaket91-1** [tomdebree/SimpDisplay#2]
Trying to figure out why my nextion display isn't updating and looking for any debugging options in case I've missed anything.
When connected to the SimpBMS and a couple of Tesla cells, the serial output and the CAN to the Victron GX device show voltages and a SOC of ~50%. The Nextion display however always shows 100% and a temp of 0. When hitting the detail button, is shows a stat of `newtxt` so I think all is pointing to the display not getting (or thinking so) serial input.

I've hooked up a USB to Serial adapter directly to the nextion connector and with a baud rate of `115200` I get output like the below, which looks right (using screen on Mac).

```
c5id.val=5���c5v.val=0���c6id.val=6���c6v.val=0���t1v.val=0���t2v.val=0���stat.txt=" Active "���soc.val=99���soc1.val=99���current.val=0���temp.val=nan���templow.val=999���temphigh.val=-999���volt.val=0���lowcell.val=5000���highcell.val=0���firm.val=220820���celldelta.val=-5000���cellbal.val=0���mNum.val=1���c1id.val=1���c1v.val=0���c2id.val=2���c2v.val=0���c3id.val=3���c3v.val=0���c4id.val=4���c4v.val=0���c5id.val=5���c5v.val=0���c6id.val=6���c6v.val=0���t1v.val=0���t2v.val=0���stat.txt=" Active "���soc.val=99���soc1.val=99���current.val=0���temp.val=nan���templow.val=999���temphigh.val=-999���volt.val=0���lowcell.val=5000���highcell.val=0���firm.val=220820���celldelta.val=-5000���cellbal.val=0���mNum.val=1���c1id.val=1���c1v.val=0���c2id.val=2���c2v.val=0���c3id.val=3���c3v.val=0���c4id.val=4���c4v.val=0���c5id.val=5���c5v.val=0���c6id.val=6���c6v.val=0���t1v.val=0���t2v.val=0���stat.txt=" Active "���soc.val=99���soc1.val=99���current.val=0���temp.val=nan���templow.val=999���temphigh.val=-999���volt.val=0���lowcell.val=5000���highcell.val=0���firm.val=220820���celldelta.val=-5000���cellbal.val=0���mNum.val=1���c1id.val=1���c1v.val=0���c2id.val=2���c2v.val=0���c3id.val=3���c3v.val=0���c4id.val=4���c4v.val=0���c5id.val=5���c5v.val=0���c6id.val=6���c6v.val=0���t1v.val=0���t2v.val=0���stat.txt=" Active "���soc.val=99���soc1.val=99���current.val=0���temp.val=nan���templow.val=999���temphigh.val=-999���volt.val=0���lowcell.val=5000���highcell.val=0���firm.val=220820���celldelta.val=-5000���cellbal.val=0���mNum.val=1���c1id.val=1���c1v.val=0���c2id.val=2���c2v.val=0���c3id.val=3���c3v.val=0���c4id.val=4���c4v.val=0���c5id.val=5���c5v.val=0���c6id.val=6���c6v.val=0���t1v.val=0���t2v.val=0���stat.txt=" Active "���soc.val=99���soc1.val=99���current.val=0
```

Are there any additional things I can do to test this or does it look like a dodgy display? 

Cheers

**Comment by Tom-evnut** [comment]
First thing to try swapping tx and rx connection.

**Comment by jaket91-1** [comment]
Hey Tom, thanks a lot for the quick response! I had the "Hmmm, that's supposed to be the RX wire" realisation just after posting this. For some reason Pin 3 on J5 is TX for me whereas the instructions on page 21 of the manual say it should be RX. I'm all sorted now, thanks again.
